import type { Job } from "@/types/entities/job";
import type { Review } from "@/types/entities/review";
import type { Company } from "@/types/entities/company";
import type { Package } from "@/types/entities/package";
import type { Payment } from "@/types/entities/payment";
import type { Application } from "@/types/entities/application";
import type { WeeklyData } from "@/types/componentTypes/areportTypes";
import type {
  AdminfetchAllUsersResponse,
  AdminFetchApplicationsReportStatsDataResponse,
  AdminFetchOverviewStatsDataResponse,
  AdminFetchReportTableDataResponse,
  AdminFetchRevenueReportStatsDataResponse,
  AdminFetchUserReportStatsDataResponse,
} from "@/types/apiTypes/adminApiTypes";
import type { Testimonial } from "@/types/entities/testimonial";

// Overview page
export const overviewUserDummyData = [
  { date: "01-08-2025", newUsers: 12, oldUsers: 40 },
  { date: "02-08-2025", newUsers: 15, oldUsers: 42 },
  { date: "03-08-2025", newUsers: 9, oldUsers: 38 },
  { date: "04-08-2025", newUsers: 14, oldUsers: 41 },
  { date: "05-08-2025", newUsers: 18, oldUsers: 44 },
  { date: "06-08-2025", newUsers: 20, oldUsers: 46 },
  { date: "07-08-2025", newUsers: 11, oldUsers: 39 },
  { date: "08-08-2025", newUsers: 17, oldUsers: 45 },
  { date: "09-08-2025", newUsers: 13, oldUsers: 40 },
  { date: "10-08-2025", newUsers: 22, oldUsers: 48 },
  { date: "11-08-2025", newUsers: 10, oldUsers: 37 },
  { date: "12-08-2025", newUsers: 19, oldUsers: 43 },
  { date: "13-08-2025", newUsers: 15, oldUsers: 42 },
  { date: "14-08-2025", newUsers: 21, oldUsers: 47 },
  { date: "15-08-2025", newUsers: 16, oldUsers: 41 },
  { date: "16-08-2025", newUsers: 23, oldUsers: 49 },
  { date: "17-08-2025", newUsers: 12, oldUsers: 39 },
  { date: "18-08-2025", newUsers: 14, oldUsers: 42 },
  { date: "19-08-2025", newUsers: 20, oldUsers: 45 },
];

export const overviewPaymentsDummyData = [
  { date: "01-08-2025", users: 12, applications: 8 },
  { date: "02-08-2025", users: 15, applications: 11 },
  { date: "03-08-2025", users: 9, applications: 5 },
  { date: "04-08-2025", users: 18, applications: 14 },
  { date: "05-08-2025", users: 22, applications: 17 },
  { date: "06-08-2025", users: 14, applications: 9 },
  { date: "07-08-2025", users: 19, applications: 13 },
  { date: "08-08-2025", users: 25, applications: 20 },
  { date: "09-08-2025", users: 11, applications: 7 },
  { date: "10-08-2025", users: 16, applications: 12 },
];

// Report page
// ✅ Dummy user Report Stats
export const dummyAdminUserReportStats: AdminFetchUserReportStatsDataResponse =
  {
    totalUsers: 1200,
    newUsers: 150,
    oldUsers: 1050,
    jobApplications: 320,
    packageUsedUsers: 480,
  };

// ✅ Dummy Applications Report Stats
export const dummyAdminApplicationsReportStats: AdminFetchApplicationsReportStatsDataResponse =
  {
    totalApplications: 210,
    successfulPlacements: 75,
  };

// ✅ Dummy Revenue Report Stats
export const dummyAdminRevenueReportStats: AdminFetchRevenueReportStatsDataResponse =
  {
    totalRevenue: 18000,
    packageRevenue: 12000,
    hiringRevenue: 6000,
  };

// ✅ Dummy overview Report Stats
export const dummyAdminOverviewStats: AdminFetchOverviewStatsDataResponse = {
  totalUsers: 2450,
  totalPackages: 120,
  totalJobsAvailable: 340,
  totalCompanies: 85,
  totalPostions: 420,
  totalApplications: 3100,
};

export const weeklyUsersDummyData: WeeklyData[] = [
  { day: "Monday", count: 120 },
  { day: "Tuesday", count: 90 },
  { day: "Wednesday", count: 100 },
  { day: "Thursday", count: 130 },
  { day: "Friday", count: 150 },
  { day: "Saturday", count: 170 },
  { day: "Sunday", count: 140 },
];

export const weeklyApplicationDummyData: WeeklyData[] = [
  { day: "Monday", count: 22 },
  { day: "Tuesday", count: 35 },
  { day: "Wednesday", count: 28 },
  { day: "Thursday", count: 31 },
  { day: "Friday", count: 44 },
  { day: "Saturday", count: 38 },
  { day: "Sunday", count: 29 },
];

export const weeklyPaymentsDummyData: WeeklyData[] = [
  { day: "Monday", count: 2000 },
  { day: "Tuesday", count: 2200 },
  { day: "Wednesday", count: 1800 },
  { day: "Thursday", count: 2500 },
  { day: "Friday", count: 3000 },
  { day: "Saturday", count: 3200 },
  { day: "Sunday", count: 2700 },
];

export const reportTableDataDummyData: AdminFetchReportTableDataResponse[] = [
  {
    date: "2025-08-01",
    jobApplications: 120,
    packagesTaken: 45,
    revenueFromJobApplications: 60000,
    revenueFromPackages: 180000,
    totalRevenue: 240000,
  },
  {
    date: "2025-08-02",
    jobApplications: 90,
    packagesTaken: 30,
    revenueFromJobApplications: 45000,
    revenueFromPackages: 120000,
    totalRevenue: 165000,
  },
  {
    date: "2025-08-03",
    jobApplications: 140,
    packagesTaken: 50,
    revenueFromJobApplications: 70000,
    revenueFromPackages: 200000,
    totalRevenue: 270000,
  },
  {
    date: "2025-08-04",
    jobApplications: 110,
    packagesTaken: 35,
    revenueFromJobApplications: 55000,
    revenueFromPackages: 140000,
    totalRevenue: 195000,
  },
  {
    date: "2025-08-05",
    jobApplications: 180,
    packagesTaken: 60,
    revenueFromJobApplications: 90000,
    revenueFromPackages: 240000,
    totalRevenue: 330000,
  },
  {
    date: "2025-08-06",
    jobApplications: 95,
    packagesTaken: 25,
    revenueFromJobApplications: 47500,
    revenueFromPackages: 100000,
    totalRevenue: 147500,
  },
  {
    date: "2025-08-07",
    jobApplications: 130,
    packagesTaken: 55,
    revenueFromJobApplications: 65000,
    revenueFromPackages: 220000,
    totalRevenue: 285000,
  },
  {
    date: "2025-08-08",
    jobApplications: 160,
    packagesTaken: 70,
    revenueFromJobApplications: 80000,
    revenueFromPackages: 280000,
    totalRevenue: 360000,
  },
  {
    date: "2025-08-09",
    jobApplications: 100,
    packagesTaken: 40,
    revenueFromJobApplications: 50000,
    revenueFromPackages: 160000,
    totalRevenue: 210000,
  },
  {
    date: "2025-08-10",
    jobApplications: 150,
    packagesTaken: 65,
    revenueFromJobApplications: 75000,
    revenueFromPackages: 260000,
    totalRevenue: 335000,
  },
];

export const revenueDummyData = [
  {
    date: "01-08-2025",
    totalRevenue: 12000,
    packageRevenue: 8000,
    hiringRevenue: 4000,
  },
  {
    date: "02-08-2025",
    totalRevenue: 15000,
    packageRevenue: 9500,
    hiringRevenue: 5500,
  },
  {
    date: "03-08-2025",
    totalRevenue: 11000,
    packageRevenue: 7000,
    hiringRevenue: 4000,
  },
  {
    date: "04-08-2025",
    totalRevenue: 17000,
    packageRevenue: 11000,
    hiringRevenue: 6000,
  },
  {
    date: "05-08-2025",
    totalRevenue: 14000,
    packageRevenue: 9000,
    hiringRevenue: 5000,
  },
  {
    date: "06-08-2025",
    totalRevenue: 18000,
    packageRevenue: 12000,
    hiringRevenue: 6000,
  },
  {
    date: "07-08-2025",
    totalRevenue: 16000,
    packageRevenue: 10000,
    hiringRevenue: 6000,
  },
  {
    date: "08-08-2025",
    totalRevenue: 20000,
    packageRevenue: 13000,
    hiringRevenue: 7000,
  },
  {
    date: "09-08-2025",
    totalRevenue: 19000,
    packageRevenue: 12500,
    hiringRevenue: 6500,
  },
  {
    date: "10-08-2025",
    totalRevenue: 22000,
    packageRevenue: 14000,
    hiringRevenue: 8000,
  },
];

export const applicationDummyData = [
  { date: "10-08-2025", totalApplicants: 120, successfulPlacements: 30 },
  { date: "11-08-2025", totalApplicants: 140, successfulPlacements: 40 },
  { date: "12-08-2025", totalApplicants: 135, successfulPlacements: 38 },
  { date: "13-08-2025", totalApplicants: 150, successfulPlacements: 45 },
  { date: "14-08-2025", totalApplicants: 160, successfulPlacements: 50 },
  { date: "15-08-2025", totalApplicants: 170, successfulPlacements: 55 },
  { date: "16-08-2025", totalApplicants: 165, successfulPlacements: 52 },
  { date: "17-08-2025", totalApplicants: 180, successfulPlacements: 60 },
  { date: "18-08-2025", totalApplicants: 190, successfulPlacements: 62 },
  { date: "19-08-2025", totalApplicants: 200, successfulPlacements: 70 },
];

// Report user dummy data
export const reportUserDummyData = [
  {
    date: "01-08-2025",
    totalUsers: 597,
    oldUsers: 266,
    newUsers: 331,
    jobApplicants: 239,
    packageUsedUsers: 141,
  },
  {
    date: "02-08-2025",
    totalUsers: 738,
    oldUsers: 446,
    newUsers: 292,
    jobApplicants: 112,
    packageUsedUsers: 126,
  },
  {
    date: "03-08-2025",
    totalUsers: 591,
    oldUsers: 445,
    newUsers: 146,
    jobApplicants: 299,
    packageUsedUsers: 52,
  },
  {
    date: "04-08-2025",
    totalUsers: 586,
    oldUsers: 436,
    newUsers: 150,
    jobApplicants: 269,
    packageUsedUsers: 105,
  },
  {
    date: "05-08-2025",
    totalUsers: 622,
    oldUsers: 452,
    newUsers: 170,
    jobApplicants: 152,
    packageUsedUsers: 25,
  },
  {
    date: "06-08-2025",
    totalUsers: 781,
    oldUsers: 512,
    newUsers: 269,
    jobApplicants: 199,
    packageUsedUsers: 175,
  },
  {
    date: "07-08-2025",
    totalUsers: 829,
    oldUsers: 488,
    newUsers: 341,
    jobApplicants: 173,
    packageUsedUsers: 87,
  },
  {
    date: "08-08-2025",
    totalUsers: 754,
    oldUsers: 389,
    newUsers: 365,
    jobApplicants: 221,
    packageUsedUsers: 142,
  },
  {
    date: "09-08-2025",
    totalUsers: 623,
    oldUsers: 355,
    newUsers: 268,
    jobApplicants: 283,
    packageUsedUsers: 67,
  },
  {
    date: "10-08-2025",
    totalUsers: 695,
    oldUsers: 400,
    newUsers: 295,
    jobApplicants: 142,
    packageUsedUsers: 132,
  },
  {
    date: "11-08-2025",
    totalUsers: 842,
    oldUsers: 576,
    newUsers: 266,
    jobApplicants: 214,
    packageUsedUsers: 151,
  },
  {
    date: "12-08-2025",
    totalUsers: 715,
    oldUsers: 419,
    newUsers: 296,
    jobApplicants: 187,
    packageUsedUsers: 124,
  },
  {
    date: "13-08-2025",
    totalUsers: 605,
    oldUsers: 310,
    newUsers: 295,
    jobApplicants: 198,
    packageUsedUsers: 91,
  },
  {
    date: "14-08-2025",
    totalUsers: 774,
    oldUsers: 432,
    newUsers: 342,
    jobApplicants: 168,
    packageUsedUsers: 139,
  },
  {
    date: "15-08-2025",
    totalUsers: 692,
    oldUsers: 401,
    newUsers: 291,
    jobApplicants: 207,
    packageUsedUsers: 112,
  },
];

// chat dummy data
export const dummyUsers = [
  {
    _id: "u1",
    fullName: "John Doe",
    profileImage: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    _id: "u2",
    fullName: "Jane Smith",
    profileImage: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    _id: "u3",
    fullName: "Alice Johnson",
    profileImage: "https://randomuser.me/api/portraits/women/68.jpg",
  },
  {
    _id: "u4",
    fullName: "Michael Brown",
    profileImage: "https://randomuser.me/api/portraits/men/76.jpg",
  },
  {
    _id: "u5",
    fullName: "Sophia Davis",
    profileImage: "https://randomuser.me/api/portraits/women/12.jpg",
  },
];

// Adminusers compoenent dummy data
export const usersDummyData: AdminfetchAllUsersResponse[] = [
  {
    _id: "1",
    fullName: "John Doe",
    email: "john.doe@example.com",
    createdAt: "1724066432987",
    isVerified: true,
    isBlocked: true,
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    _id: "2",
    fullName: "Jane Smith",
    email: "jane.smith@example.com",
    createdAt: "1724066432987",
    isVerified: false,
    isBlocked: true,
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    _id: "3",
    fullName: "Michael Johnson",
    email: "michael.johnson@example.com",
    createdAt: "1724066432987",
    isVerified: true,
    isBlocked: false,
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    _id: "4",
    fullName: "Emily Davis",
    email: "emily.davis@example.com",
    createdAt: "1724066432987",
    isVerified: true,
    isBlocked: true,
    profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    _id: "5",
    fullName: "David Wilson",
    email: "david.wilson@example.com",
    createdAt: "1724066432987",
    isVerified: false,
    isBlocked: false,
    profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    _id: "6",
    fullName: "Sophia Martinez",
    email: "sophia.martinez@example.com",
    createdAt: "1724066432987",
    isVerified: true,
    isBlocked: true,
    profileImage: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    _id: "7",
    fullName: "James Brown",
    email: "james.brown@example.com",
    createdAt: "1724066432987",
    isVerified: false,
    isBlocked: true,
    profileImage: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    _id: "8",
    fullName: "Olivia Taylor",
    email: "olivia.taylor@example.com",
    createdAt: "1724066432987",
    isVerified: true,
    isBlocked: true,
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    _id: "9",
    fullName: "William Anderson",
    email: "william.anderson@example.com",
    createdAt: "1724066432987",
    isVerified: false,
    isBlocked: false,
    profileImage: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    _id: "10",
    fullName: "Ava Thomas",
    email: "ava.thomas@example.com",
    createdAt: "1724066432987",
    isVerified: true,
    isBlocked: true,
    profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
  },
];

// Company dummy data
export const companiesDummyData: Company[] = [
  {
    _id: "c1",
    companyName: "TechNova Solutions",
    companyLogo:
      "https://img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
    email: "hr@technova.com",
    createdAt: "2024-08-01T10:20:30Z",
    updatedAt: "2024-08-10T14:25:00Z",
    availableJobCount: 12,
    availablePostsWithCount: [
      { post: "Software Engineer", count: 5 },
      { post: "UI/UX Designer", count: 3 },
      { post: "QA Tester", count: 4 },
    ],
  },
  {
    _id: "c2",
    companyName: "GreenField Pvt Ltd",
    companyLogo:
      "https://img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
    email: "careers@greenfield.com",
    createdAt: "2024-07-12T09:15:10Z",
    updatedAt: "2024-08-05T11:45:00Z",
    availableJobCount: 8,
    availablePostsWithCount: [
      { post: "Backend Developer", count: 3 },
      { post: "Project Manager", count: 2 },
      { post: "HR Executive", count: 3 },
    ],
  },
  {
    _id: "c3",
    companyName: "Skyline Industries",
    companyLogo:
      "https://img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
    email: "jobs@skyline.com",
    createdAt: "2024-06-20T12:05:00Z",
    updatedAt: "2024-07-01T08:40:00Z",
    availableJobCount: 15,
    availablePostsWithCount: [
      { post: "Mechanical Engineer", count: 6 },
      { post: "Data Analyst", count: 4 },
      { post: "Business Analyst", count: 5 },
    ],
  },
  {
    _id: "c4",
    companyName: "BrightWave Tech",
    companyLogo:
      "https://img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
    email: "brightwave.hr@gmail.com",
    createdAt: "2024-05-15T14:10:00Z",
    updatedAt: "2024-06-01T17:45:00Z",
    availableJobCount: 6,
    availablePostsWithCount: [
      { post: "Mobile App Developer", count: 2 },
      { post: "Cloud Engineer", count: 4 },
    ],
  },
  {
    _id: "c5",
    companyName: "NextGen Labs",
    companyLogo:
      "https://img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
    email: "recruit@nextgenlabs.io",
    createdAt: "2024-09-01T08:25:00Z",
    updatedAt: "2024-09-05T09:10:00Z",
    availableJobCount: 10,
    availablePostsWithCount: [
      { post: "AI Engineer", count: 4 },
      { post: "Data Scientist", count: 3 },
      { post: "Research Intern", count: 3 },
    ],
  },
  {
    _id: "c6",
    companyName: "BlueOcean Ventures",
    companyLogo:
      "https://img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
    email: "talent@blueocean.com",
    createdAt: "2024-03-12T07:45:00Z",
    updatedAt: "2024-04-01T10:30:00Z",
    availableJobCount: 9,
    availablePostsWithCount: [
      { post: "Finance Analyst", count: 3 },
      { post: "Marketing Specialist", count: 4 },
      { post: "Operations Manager", count: 2 },
    ],
  },
  {
    _id: "c7",
    companyName: "UrbanWorks Pvt Ltd",
    companyLogo:
      "https://img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
    email: "urbanworks.hr@jobs.com",
    createdAt: "2024-01-25T11:20:00Z",
    updatedAt: "2024-02-14T13:40:00Z",
    availableJobCount: 7,
    availablePostsWithCount: [
      { post: "Architect", count: 3 },
      { post: "Civil Engineer", count: 4 },
    ],
  },
  {
    _id: "c8",
    companyName: "CyberNet Systems",
    companyLogo:
      "https://img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
    email: "cybernet.jobs@company.com",
    createdAt: "2024-02-10T10:15:00Z",
    updatedAt: "2024-03-01T12:10:00Z",
    availableJobCount: 14,
    availablePostsWithCount: [
      { post: "Network Engineer", count: 5 },
      { post: "Security Analyst", count: 4 },
      { post: "System Admin", count: 5 },
    ],
  },
  {
    _id: "c9",
    companyName: "QuantumSoft",
    companyLogo:
      "https://img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
    email: "quantumsoft@hr.com",
    createdAt: "2024-04-08T09:40:00Z",
    updatedAt: "2024-04-20T11:00:00Z",
    availableJobCount: 11,
    availablePostsWithCount: [
      { post: "Frontend Developer", count: 4 },
      { post: "Fullstack Engineer", count: 3 },
      { post: "DevOps Engineer", count: 4 },
    ],
  },
  {
    _id: "c10",
    companyName: "AeroSpace Dynamics",
    companyLogo:
      "https://img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg",
    email: "careers@aerospace.com",
    createdAt: "2024-06-01T13:00:00Z",
    updatedAt: "2024-06-15T16:20:00Z",
    availableJobCount: 5,
    availablePostsWithCount: [
      { post: "Aerospace Engineer", count: 3 },
      { post: "CAD Designer", count: 2 },
    ],
  },
];

// Jobs dummy data
export const jobsDummyData: Job[] = [
  {
    _id: "j1",
    companyName: "TechNova Solutions",
    designation: "Software Engineer",
    vacancy: 5,
    createdAt: "2025-08-01T10:30:00Z",
    updatedAt: "2025-08-15T12:45:00Z",
  },
  {
    _id: "j2",
    companyName: "TechNova Solutions",
    designation: "UI/UX Designer",
    vacancy: 3,
    createdAt: "2025-07-20T09:00:00Z",
    updatedAt: "2025-08-10T11:15:00Z",
  },
  {
    _id: "j3",
    companyName: "TechNova Solutions",
    designation: "QA Tester",
    vacancy: 4,
    createdAt: "2025-07-10T08:20:00Z",
    updatedAt: "2025-08-12T14:00:00Z",
  },
  {
    _id: "j4",
    companyName: "GreenField Pvt Ltd",
    designation: "Backend Developer",
    vacancy: 3,
    createdAt: "2025-06-18T13:00:00Z",
    updatedAt: "2025-08-11T15:30:00Z",
  },
  {
    _id: "j5",
    companyName: "GreenField Pvt Ltd",
    designation: "Project Manager",
    vacancy: 2,
    createdAt: "2025-06-25T10:15:00Z",
    updatedAt: "2025-08-14T09:45:00Z",
  },
  {
    _id: "j6",
    companyName: "GreenField Pvt Ltd",
    designation: "HR Executive",
    vacancy: 3,
    createdAt: "2025-07-05T11:10:00Z",
    updatedAt: "2025-08-13T10:20:00Z",
  },
  {
    _id: "j7",
    companyName: "Skyline Industries",
    designation: "Mechanical Engineer",
    vacancy: 6,
    createdAt: "2025-05-30T09:00:00Z",
    updatedAt: "2025-08-16T13:15:00Z",
  },
  {
    _id: "j8",
    companyName: "Skyline Industries",
    designation: "Data Analyst",
    vacancy: 4,
    createdAt: "2025-07-12T08:40:00Z",
    updatedAt: "2025-08-17T14:10:00Z",
  },
  {
    _id: "j9",
    companyName: "Skyline Industries",
    designation: "Business Analyst",
    vacancy: 5,
    createdAt: "2025-06-08T12:25:00Z",
    updatedAt: "2025-08-18T16:30:00Z",
  },
  {
    _id: "j10",
    companyName: "BrightWave Tech",
    designation: "Mobile App Developer",
    vacancy: 2,
    createdAt: "2025-07-22T10:50:00Z",
    updatedAt: "2025-08-18T11:05:00Z",
  },
];

// Package dummy data
export const packageDummyData: Package[] = [
  {
    _id: "p1",
    packageName: "Dubai Essentials",
    description:
      "Perfect 3-day trip covering the must-see attractions of Dubai.",
    price: "1500 AED",
    features: [
      "3 Nights Hotel Stay (3-Star)",
      "Airport Transfers",
      "Dubai City Tour",
      "Desert Safari with BBQ Dinner",
      "Dhow Cruise at Dubai Marina",
    ],
    createdAt: "2025-07-01T10:00:00Z",
    updatedAt: "2025-08-15T09:30:00Z",
  },
  {
    _id: "p2",
    packageName: "Luxury Dubai Getaway",
    description:
      "Experience Dubai in luxury with 5-star accommodation and premium tours.",
    price: "4500 AED",
    features: [
      "4 Nights 5-Star Hotel Stay",
      "Airport Pick & Drop in Luxury Car",
      "Burj Khalifa 148th Floor VIP Access",
      "Premium Desert Safari with Quad Biking",
      "Dubai Marina Yacht Dinner Cruise",
      "Shopping Tour with Personal Guide",
      "Day Trip to Abu Dhabi",
    ],
    createdAt: "2025-06-20T12:15:00Z",
    updatedAt: "2025-08-10T11:45:00Z",
  },
  {
    _id: "p3",
    packageName: "Adventure in Dubai",
    description: "Thrilling Dubai adventure package for adrenaline seekers.",
    price: "3200 AED",
    features: [
      "3 Nights Hotel Stay (4-Star)",
      "Skydiving over Palm Jumeirah",
      "Dune Bashing & Sandboarding",
      "Atlantis Aquaventure Waterpark",
      "Jet Ski Experience in Jumeirah Beach",
      "Dubai Frame & Museum of the Future",
    ],
    createdAt: "2025-07-10T08:20:00Z",
    updatedAt: "2025-08-12T14:00:00Z",
  },
  {
    _id: "p4",
    packageName: "Family Fun Dubai",
    description:
      "Special family-friendly package with activities for all ages.",
    price: "2800 AED",
    features: [
      "5 Nights Hotel Stay (Family Suite)",
      "Airport Transfers",
      "Dubai Aquarium & Underwater Zoo",
      "Legoland & Motiongate Dubai",
      "Global Village Visit",
      "Desert Safari with Kids Activities",
      "IMG Worlds of Adventure",
      "Day Trip to Miracle Garden",
    ],
    createdAt: "2025-07-18T09:40:00Z",
    updatedAt: "2025-08-14T10:20:00Z",
  },
  {
    _id: "p5",
    packageName: "Romantic Dubai Escape",
    description:
      "A romantic Dubai experience tailored for couples & honeymooners.",
    price: "3700 AED",
    features: [
      "4 Nights Luxury Hotel Stay",
      "Private Airport Transfers",
      "Romantic Dinner on Dubai Creek",
      "Sunset Desert Safari",
      "Couple Spa Experience",
      "Burj Khalifa Sky Lounge Visit",
      "Hot Air Balloon Ride",
    ],
    createdAt: "2025-07-25T11:10:00Z",
    updatedAt: "2025-08-16T13:45:00Z",
  },
];

// Payment dummy data
export const paymentsDummyData: Payment[] = [
  {
    _id: "pay_001",
    transactionId: "TXN987654321",
    userId: "usr_101",
    username: "john_doe",
    screenshot: "/uploads/payments/txn1.png",
    discountAmount: "50 AED",
    totalAmount: "1450 AED",
    paymentStatus: "Completed",
    createdAt: "2025-08-01T10:15:00Z",
    updatedAt: "2025-08-01T10:20:00Z",
  },
  {
    _id: "pay_002",
    transactionId: "TXN123456789",
    userId: "usr_102",
    username: "sarah_lee",
    screenshot: "/uploads/payments/txn2.png",
    discountAmount: "0 AED",
    totalAmount: "3200 AED",
    paymentStatus: "Pending",
    createdAt: "2025-08-05T09:30:00Z",
    updatedAt: "2025-08-05T09:35:00Z",
  },
  {
    _id: "pay_003",
    transactionId: "TXN456789123",
    userId: "usr_103",
    username: "mike_smith",
    screenshot: "/uploads/payments/txn3.png",
    discountAmount: "200 AED",
    totalAmount: "4300 AED",
    paymentStatus: "Completed",
    createdAt: "2025-08-10T14:45:00Z",
    updatedAt: "2025-08-10T15:00:00Z",
  },
  {
    _id: "pay_004",
    transactionId: "TXN789123456",
    userId: "usr_104",
    username: "anita_kumar",
    screenshot: "/uploads/payments/txn4.png",
    discountAmount: "100 AED",
    totalAmount: "2700 AED",
    paymentStatus: "Failed",
    createdAt: "2025-08-12T08:20:00Z",
    updatedAt: "2025-08-12T08:25:00Z",
  },
  {
    _id: "pay_005",
    transactionId: "TXN654321987",
    userId: "usr_105",
    username: "david_wong",
    screenshot: "/uploads/payments/txn5.png",
    discountAmount: "150 AED",
    totalAmount: "3550 AED",
    paymentStatus: "Completed",
    createdAt: "2025-08-15T11:10:00Z",
    updatedAt: "2025-08-15T11:20:00Z",
  },
];

// Review dummy data
export const reviewsDummyData: Review[] = [
  {
    _id: "rev_001",
    userId: "usr_101",
    username: "john_doe",
    job: "Software Engineer",
    text: "Amazing experience! The platform was easy to use and really helped me find opportunities quickly.",
    createdAt: "2025-08-01T09:15:00Z",
    updatedAt: "2025-08-01T09:20:00Z",
  },
  {
    _id: "rev_002",
    userId: "usr_102",
    username: "sarah_lee",
    job: "UI/UX Designer",
    text: "Loved the clean interface. However, I wish there were more filtering options while browsing jobs.",
    createdAt: "2025-08-03T11:45:00Z",
    updatedAt: "2025-08-03T11:50:00Z",
  },
  {
    _id: "rev_003",
    userId: "usr_103",
    username: "mike_smith",
    job: "Data Analyst",
    text: "Support team was quick to respond when I had issues. Overall, a reliable service.",
    createdAt: "2025-08-06T14:10:00Z",
    updatedAt: "2025-08-06T14:20:00Z",
  },
  {
    _id: "rev_004",
    userId: "usr_104",
    username: "anita_kumar",
    job: "Project Manager",
    text: "The job recommendations were very relevant. It saved me a lot of time during my search.",
    createdAt: "2025-08-10T16:30:00Z",
    updatedAt: "2025-08-10T16:40:00Z",
  },
  {
    _id: "rev_005",
    userId: "usr_105",
    username: "david_wong",
    job: "Marketing Specialist",
    text: "Great value for money! The premium features really boosted my visibility.",
    createdAt: "2025-08-12T18:00:00Z",
    updatedAt: "2025-08-12T18:05:00Z",
  },
];

// Application dummy data
export const applicationsDummyData: Application[] = [
  {
    _id: "app_001",
    userId: "usr_101",
    jobId: "job_501",
    cvLink: "https://example.com/cv/john_doe.pdf",
    createdAt: "2025-08-01T09:30:00Z",
    updatedAt: "2025-08-01T09:40:00Z",
    username: "John Doe",
    company: "TechNova Solutions",
    designation: "Software Engineer",
  },
  {
    _id: "app_002",
    userId: "usr_102",
    jobId: "job_502",
    cvLink: "https://example.com/cv/sarah_lee.pdf",
    createdAt: "2025-08-02T10:15:00Z",
    updatedAt: "2025-08-02T10:25:00Z",
    username: "Sarah Lee",
    company: "DesignHive Studios",
    designation: "UI/UX Designer",
  },
  {
    _id: "app_003",
    userId: "usr_103",
    jobId: "job_503",
    cvLink: "https://example.com/cv/mike_smith.pdf",
    createdAt: "2025-08-04T13:20:00Z",
    updatedAt: "2025-08-04T13:30:00Z",
    username: "Mike Smith",
    company: "DataVision Analytics",
    designation: "Data Analyst",
  },
  {
    _id: "app_004",
    userId: "usr_104",
    jobId: "job_504",
    cvLink: "https://example.com/cv/anita_kumar.pdf",
    createdAt: "2025-08-06T15:45:00Z",
    updatedAt: "2025-08-06T15:55:00Z",
    username: "Anita Kumar",
    company: "AgileWorks Ltd.",
    designation: "Project Manager",
  },
  {
    _id: "app_005",
    userId: "usr_105",
    jobId: "job_505",
    cvLink: "https://example.com/cv/david_wong.pdf",
    createdAt: "2025-08-08T17:00:00Z",
    updatedAt: "2025-08-08T17:10:00Z",
    username: "David Wong",
    company: "MarketEdge Global",
    designation: "Marketing Specialist",
  },
];

export const MOCK_COMPANIES = [
  {
    id: "co-1",
    name: "Google",
    logo: "https://logo.clearbit.com/google.com",
    tagline: "Trusted by teams worldwide",
    trustScore: 80,
    since: 1998,
    industries: ["Cloud", "AI"],
  },
  {
    id: "co-2",
    name: "Microsoft",
    logo: "https://logo.clearbit.com/microsoft.com",
    tagline: "Powering digital transformation",
    trustScore: 81,
    since: 1999,
    industries: ["Cloud", "AI"],
  },
  {
    id: "co-3",
    name: "Amazon",
    logo: "https://logo.clearbit.com/amazon.com",
    tagline: "Delivering value at scale",
    trustScore: 82,
    since: 2000,
    industries: ["Ecommerce", "Logistics"],
  },
  {
    id: "co-4",
    name: "Netflix",
    logo: "https://logo.clearbit.com/netflix.com",
    tagline: "Streaming innovation",
    trustScore: 83,
    since: 2001,
    industries: ["Media", "Streaming"],
  },
  {
    id: "co-5",
    name: "Meta",
    logo: "https://logo.clearbit.com/meta.com",
    tagline: "Connecting communities",
    trustScore: 84,
    since: 2002,
    industries: ["DevTools", "SaaS"],
  },
  {
    id: "co-6",
    name: "Stripe",
    logo: "https://logo.clearbit.com/stripe.com",
    tagline: "Trusted by teams worldwide",
    trustScore: 85,
    since: 2003,
    industries: ["Fintech", "Payments"],
  },
  {
    id: "co-7",
    name: "Shopify",
    logo: "https://logo.clearbit.com/shopify.com",
    tagline: "Powering digital transformation",
    trustScore: 86,
    since: 2004,
    industries: ["Ecommerce", "Logistics"],
  },
  {
    id: "co-8",
    name: "Airbnb",
    logo: "https://logo.clearbit.com/airbnb.com",
    tagline: "Delivering value at scale",
    trustScore: 87,
    since: 2005,
    industries: ["Media", "Streaming"],
  },
  {
    id: "co-9",
    name: "Uber",
    logo: "https://logo.clearbit.com/uber.com",
    tagline: "Streaming innovation",
    trustScore: 88,
    since: 2006,
    industries: ["DevTools", "SaaS"],
  },
  {
    id: "co-10",
    name: "PayPal",
    logo: "https://logo.clearbit.com/paypal.com",
    tagline: "Connecting communities",
    trustScore: 89,
    since: 2007,
    industries: ["Fintech", "Payments"],
  },
  {
    id: "co-11",
    name: "Adobe",
    logo: "https://logo.clearbit.com/adobe.com",
    tagline: "Trusted by teams worldwide",
    trustScore: 90,
    since: 2008,
    industries: ["Cloud", "AI"],
  },
  {
    id: "co-12",
    name: "Salesforce",
    logo: "https://logo.clearbit.com/salesforce.com",
    tagline: "Powering digital transformation",
    trustScore: 91,
    since: 2009,
    industries: ["Ecommerce", "Logistics"],
  },
  {
    id: "co-13",
    name: "Intel",
    logo: "https://logo.clearbit.com/intel.com",
    tagline: "Delivering value at scale",
    trustScore: 92,
    since: 2010,
    industries: ["Fintech", "Payments"],
  },
  {
    id: "co-14",
    name: "NVIDIA",
    logo: "https://logo.clearbit.com/nvidia.com",
    tagline: "Streaming innovation",
    trustScore: 93,
    since: 2011,
    industries: ["Media", "Streaming"],
  },
  {
    id: "co-15",
    name: "Atlassian",
    logo: "https://logo.clearbit.com/atlassian.com",
    tagline: "Connecting communities",
    trustScore: 94,
    since: 2012,
    industries: ["DevTools", "SaaS"],
  },
  {
    id: "co-16",
    name: "Twilio",
    logo: "https://logo.clearbit.com/twilio.com",
    tagline: "Trusted by teams worldwide",
    trustScore: 95,
    since: 2013,
    industries: ["Fintech", "Payments"],
  },
  {
    id: "co-17",
    name: "Spotify",
    logo: "https://logo.clearbit.com/spotify.com",
    tagline: "Powering digital transformation",
    trustScore: 96,
    since: 2014,
    industries: ["Media", "Streaming"],
  },
  {
    id: "co-18",
    name: "Zoom",
    logo: "https://logo.clearbit.com/zoom.us",
    tagline: "Delivering value at scale",
    trustScore: 97,
    since: 2015,
    industries: ["DevTools", "SaaS"],
  },
  {
    id: "co-19",
    name: "DoorDash",
    logo: "https://logo.clearbit.com/doordash.com",
    tagline: "Streaming innovation",
    trustScore: 98,
    since: 2016,
    industries: ["Ecommerce", "Logistics"],
  },
];

// Reviews compoenent constats
export const dummyTestimonials: Testimonial[] = [
  {
    _id: "1",
    clientName: "Charles Dickens",
    clientPhoto: "/images/charles-dickens.jpg", // placeholder image
    designation: "Author - A Tale of Two Cities",
    testimonial:
      "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair.",
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "2",
    clientName: "William Shakespeare",
    clientPhoto: "/images/shakespeare.jpg",
    designation: "Playwright - Hamlet",
    testimonial:
      "To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer The slings and arrows of outrageous fortune, Or to take Arms against a Sea of troubles, And by opposing end them: to die, to sleep.",
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "3",
    clientName: "Edgar Allan Poe",
    clientPhoto: "/images/poe.jpg",
    designation: "Poet - A Dream Within a Dream",
    testimonial: "All that we see or seem is but a dream within a dream.",
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "4",
    clientName: "Jane Austen",
    clientPhoto: "/images/jane-austen.jpg",
    designation: "Author - Pride and Prejudice",
    testimonial:
      "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "5",
    clientName: "Herman Melville",
    clientPhoto: "/images/melville.jpg",
    designation: "Author - Moby-Dick",
    testimonial:
      "Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.",
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
